create or replace PROCEDURE CREER_SPC_POS_CAP (TMP_CODE_MCP VARCHAR2, TMP_ID_SPC NUMBER) AS

  CURSOR curs_cap is
    select ID_CAP from CAPACITE, FAMILLE_COMPETENCE, DOMAINE_COMPETENCE
    where DOMAINE_COMPETENCE.CODE_MCP = TMP_CODE_MCP
    and DOMAINE_COMPETENCE.ID_DC = FAMILLE_COMPETENCE.ID_DC
    and FAMILLE_COMPETENCE.ID_FC = CAPACITE.ID_FC;

BEGIN

  for p in curs_cap
    loop
      INSERT INTO POSITIONNEMENT (ID_SPC, ID_CAP, TYPE_POSITIONNEMENT, NIVEAU_COMPETENCE)
      VALUES (TMP_ID_SPC, p.ID_CAP, 'MAT' ,null);
    end loop;

END;
/
