create or replace PROCEDURE CREER_SPC_POS_FC (TMP_CODE_MCP VARCHAR2, TMP_ID_SPC NUMBER) AS

  CURSOR curs_fc is
    select ID_FC from FAMILLE_COMPETENCE, DOMAINE_COMPETENCE
    where DOMAINE_COMPETENCE.CODE_MCP = TMP_CODE_MCP
    and DOMAINE_COMPETENCE.ID_DC = FAMILLE_COMPETENCE.ID_DC;

BEGIN


  for p in curs_fc
    loop
      INSERT INTO POSITIONNEMENT (ID_SPC, ID_FC, TYPE_POSITIONNEMENT, NIVEAU_COMPETENCE)
      VALUES (TMP_ID_SPC, p.ID_FC, 'MAT' ,null);
    end loop;

END;
/
