-- INSERTING into DOMAINE
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('ENS','TYPE_AUTH','Enseignant');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('ETU','TYPE_AUTH','Etudiant');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('DIP','TYPE_AUTH','Diplômé');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('ENT','TYPE_AUTH','Entreprise');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('RECH','PROC_STAGE','Recherche en cours');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('EC','PROC_STAGE','Stage en cours');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('TUT','PROC_STAGE','Tuteurs attribués');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('SOUT','PROC_STAGE','Sessions de soutenance définies');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('EVAL','PROC_STAGE','Stages évalués');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('O','OUNO','Oui');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('N','OUNO','Non');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('LP','LSEL','Liste principale');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('LA','LSEL','Liste d''attente');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('NON','MAD','Non');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('TC','MAD','Au tuteur de la compagnie');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('ETU','MAD','Aux étudiants et tuteur de la compagnie');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('ENC','PRSE','En cours');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('TER','PRSE','Terminé');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('CON','RCAN','Confirmé');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('ANN','RCAN','Annulé');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('NRE','RCAN','Non répondu');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('H','SEXE','M.');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('L','SEXE','Mlle');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('F','SEXE','Mme');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('CEL','SITU','Célibataire');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('MAR','SITU','Marié(e)');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('VEU','SITU','Veuf(ve)');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('DIV','SITU','Divorcé(e)');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('URL','TRES','URL');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('DOC','TRES','Document');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('LOG','TRES','Logiciel');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('OUV','TRES','Ouvrage');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('DIV','TRES','Divers');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('OBS','ETAT','Obsolète');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('DIS','ETAT','Disponible');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('EVO','ETAT','En cours d''évolution');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('ELA','ETAT','En cours d''élaboration');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('WIN','OS','MS Windows');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('LIN','OS','Linux');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('AUT','OS','Autres systèmes d''exploitation');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('PAP','FDOC','Format Papier');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('PDF','FDOC','Format PDF');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('DOC','FDOC','Format Word');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('HTM','FDOC','Format HTML');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('XLS','FDOC','Format Excels');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('PPT','FDOC','Format Power Point');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('TXT','FDOC','Format Texte');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('SQL','FDOC','Format SQL');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('VSD','FDOC','Format Visio');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('MPP','FDOC','Format Microsoft Project');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('AUT','FDOC','Autres Formats');
Insert into "DOMAINE" ("CODE_VALEUR","SIGLE_DOMAINE","DESIGNATION") values ('CD','TRES','CD');
