-- INSERTING into AFFECTATION_ETUDIANT
Insert into "AFFECTATION_ETUDIANT" ("ID_FA","NO_ETUDIANT_NAT","CHARGE","CONSOLIDATEUR") values (50,'1493003704n',4,'N');
Insert into "AFFECTATION_ETUDIANT" ("ID_FA","NO_ETUDIANT_NAT","CHARGE","CONSOLIDATEUR") values (50,'1492057895k',6,'O');
Insert into "AFFECTATION_ETUDIANT" ("ID_FA","NO_ETUDIANT_NAT","CHARGE","CONSOLIDATEUR") values (51,'06816q06pf3',2,'N');
Insert into "AFFECTATION_ETUDIANT" ("ID_FA","NO_ETUDIANT_NAT","CHARGE","CONSOLIDATEUR") values (51,'1499110659h',4,'O');
