-- INSERTING into EC
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (50,1,'pIN',3,'partie de pinball',9);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (7,1,'TEX',2,'Techniques d''Expression',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (8,2,'GCL',3,'Gestion de Configuration Logiciel',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (9,4,'ANA',2,'Analyse',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (10,4,'COD',3,'Codage - Tests Unitaires',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (11,4,'INT',4,'Intégration - Qualification',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (12,4,'CON',5,'Conception Logiciel',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (13,5,'SUP',1,'Support Technique',1);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (14,5,'DU',2,'Documentation Utilisateur',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (15,5,'INS',3,'Installation - Déploiement',1);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (16,5,'SMO',4,'Support Méthode et Outils',1);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (17,3,'RAP',2,'Rapport',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (18,3,'SOU',3,'Soutenanace',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (1,1,'ANG',1,'Anglais',4);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (2,2,'CDP',1,'Conduite de Projet Logiciel',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (3,2,'AQL',2,'Assurance Qualité Logiciel',1);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (4,3,'STA',1,'Travail',6);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (5,4,'CB',1,'Capture des Besoins',2);
Insert into "EC" ("ID_EC","ID_UE","SIGLE_EC","NO_EC","DESIGNATION","ECTS") values (6,4,'AT',6,'Architecture Technique',3);
