REM 
REM  Création du schéma utilisateur FA10
REM

create user FA10 identified by FA10
	default tablespace SIGILI
	temporary tablespace SIGILI_TEMP
	account unlock;
ALTER USER FA10 DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO FA10;
grant CONNECT,RESOURCE to FA10;
GRANT CREATE SEQUENCE TO FA10;
GRANT CREATE SYNONYM TO FA10;
GRANT CREATE TABLE TO FA10;
GRANT CREATE TRIGGER TO FA10;
GRANT CREATE TYPE TO FA10;
GRANT CREATE VIEW TO FA10;



REM 
REM Step 2 - Attribution de droits spécifiques XML DB
REM

GRANT ALTER ANY TRIGGER TO FA10;
GRANT ALTER SESSION TO FA10;
GRANT ALTER USER TO FA10;
GRANT ANALYZE ANY TO FA10;
GRANT ANALYZE ANY DICTIONARY TO FA10;
GRANT CREATE ANY MATERIALIZED VIEW TO FA10;
GRANT CREATE ANY PROCEDURE TO FA10;
GRANT CREATE ANY TABLE TO FA10;
GRANT CREATE ANY TRIGGER TO FA10;
GRANT CREATE ANY TYPE TO FA10;
GRANT CREATE ANY VIEW TO FA10;
GRANT CREATE INDEXTYPE TO FA10;
GRANT CREATE LIBRARY TO FA10;
GRANT CREATE OPERATOR TO FA10;
GRANT CREATE PUBLIC SYNONYM TO FA10;
GRANT CREATE SESSION TO FA10;
GRANT CREATE TRIGGER TO FA10;
GRANT CREATE VIEW TO FA10;
GRANT DEBUG ANY PROCEDURE TO FA10;
GRANT DEBUG CONNECT SESSION TO FA10;
GRANT DROP ANY TRIGGER TO FA10;
GRANT DROP PUBLIC SYNONYM TO FA10;
GRANT GRANT ANY PRIVILEGE TO FA10;
GRANT GRANT ANY ROLE TO FA10;
GRANT QUERY REWRITE TO FA10;
GRANT UNLIMITED TABLESPACE TO FA10;
GRANT EXECUTE ON "CTXSYS"."CTX_DDL" TO FA10;
GRANT EXECUTE ON "CTXSYS"."CTX_OUTPUT" TO FA10;
GRANT EXECUTE ON "SYS"."CHECK_UPGRADE" TO FA10;
GRANT EXECUTE ON "SYS"."DBMS_REGISTRY" TO FA10;
GRANT EXECUTE ON "SYS"."DBMS_RLS" TO FA10;
GRANT EXECUTE ON "SYS"."DBMS_SYS_SQL" TO FA10;
GRANT EXECUTE ON "SYS"."SET_TABLESPACE" TO FA10;
GRANT SELECT ON "SYS"."USER$" TO FA10;
GRANT EXECUTE ON "SYS"."DBMS_XDB" TO FA10;
GRANT "CONNECT" TO FA10;
GRANT "CTXAPP" TO FA10;
GRANT "JAVAUSERPRIV" TO FA10;
GRANT "RESOURCE" TO FA10;
GRANT "XDBADMIN" TO FA10;
GRANT "XDBWEBSERVICES" TO FA10;