SPOOL deltas.lst

PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~ Creation des VUES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
@@03-DELTAS\GLOBAL\VUES.vw


PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
PROMPT~~~~~~~~~~~~~~~~~~~ Lancement des API DELTAS par CSCI ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;

PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CSCI_ADM ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
@@03-DELTAS\CSCI_ADM\AUT.PKS
@@03-DELTAS\CSCI_ADM\AUT.PKB
@@03-DELTAS\CSCI_ADM\AUT.TRG

@@03-DELTAS\CSCI_ADM\COM.PKS
@@03-DELTAS\CSCI_ADM\COM.PKB
@@03-DELTAS\CSCI_ADM\COM.TRG

@@03-DELTAS\CSCI_ADM\EMP.PKS
@@03-DELTAS\CSCI_ADM\EMP.PKB
@@03-DELTAS\CSCI_ADM\EMP.TRG

@@03-DELTAS\CSCI_ADM\ENS.PKS
@@03-DELTAS\CSCI_ADM\ENS.PKB
@@03-DELTAS\CSCI_ADM\ENS.TRG

@@03-DELTAS\CSCI_ADM\ENT.PKS
@@03-DELTAS\CSCI_ADM\ENT.PKB
@@03-DELTAS\CSCI_ADM\ENT_ads.sql
@@03-DELTAS\CSCI_ADM\ENT_ais.sql
@@03-DELTAS\CSCI_ADM\ENT_aus.sql
@@03-DELTAS\CSCI_ADM\ENT_bdr.sql
@@03-DELTAS\CSCI_ADM\ENT_bds.sql
@@03-DELTAS\CSCI_ADM\ENT_bir.sql
@@03-DELTAS\CSCI_ADM\ENT_bis.sql
@@03-DELTAS\CSCI_ADM\ENT_bus.sql
@@03-DELTAS\CSCI_ADM\ENT_bur.sql

@@03-DELTAS\CSCI_ADM\ETU.PKS
@@03-DELTAS\CSCI_ADM\ETU.PKB
@@03-DELTAS\CSCI_ADM\ETU.TRG

@@03-DELTAS\CSCI_ADM\INV.PKS
@@03-DELTAS\CSCI_ADM\INV.PKB
@@03-DELTAS\CSCI_ADM\INV.TRG

@@03-DELTAS\CSCI_ADM\PRO.PKS
@@03-DELTAS\CSCI_ADM\PRO.PKB
@@03-DELTAS\CSCI_ADM\PRO.TRG

PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CSCI_CON ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
@@03-DELTAS\CSCI_CON\RES.PKS
@@03-DELTAS\CSCI_CON\RES.PKB
@@03-DELTAS\CSCI_CON\RES.TRG

@@03-DELTAS\CSCI_CON\VFAS.PKS
@@03-DELTAS\CSCI_CON\VFAS.PKB
@@03-DELTAS\CSCI_CON\VFAS.TRG

PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CSCI_RAP ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
@@03-DELTAS\CSCI_RAP\EC.PKS
@@03-DELTAS\CSCI_RAP\EC.PKB
@@03-DELTAS\CSCI_RAP\EC.TRG

@@03-DELTAS\CSCI_RAP\PAP.PKS
@@03-DELTAS\CSCI_RAP\PAP.PKB
@@03-DELTAS\CSCI_RAP\PAP.TRG

PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CSCI_STA ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
@@03-DELTAS\CSCI_STA\CODN.PKS
@@03-DELTAS\CSCI_STA\CODN.PKB
@@03-DELTAS\CSCI_STA\CODN.TRG

@@03-DELTAS\CSCI_STA\CTS.PKS
@@03-DELTAS\CSCI_STA\CTS.PKB
@@03-DELTAS\CSCI_STA\CTS.TRG

@@03-DELTAS\CSCI_STA\EVAE.PKS
@@03-DELTAS\CSCI_STA\EVAE.PKB
@@03-DELTAS\CSCI_STA\EVAE.TRG
@@03-DELTAS\CSCI_STA\EVAE_AIR_AUR.sql

@@03-DELTAS\CSCI_STA\NOTS.PKS
@@03-DELTAS\CSCI_STA\NOTS.PKB
@@03-DELTAS\CSCI_STA\NOTS.TRG

@@03-DELTAS\CSCI_STA\OFF.PKS
@@03-DELTAS\CSCI_STA\OFF.PKB
@@03-DELTAS\CSCI_STA\OFF.TRG

@@03-DELTAS\CSCI_STA\STRE.PKS
@@03-DELTAS\CSCI_STA\STRE.PKB
@@03-DELTAS\CSCI_STA\STRE.TRG

@@03-DELTAS\CSCI_STA\STA_AIR.sql
@@03-DELTAS\CSCI_STA\STA_BIR.sql

@@03-DELTAS\CSCI_STA\STG_BUR.sql

@@03-DELTAS\CSCI_STA\NOTE_AUR.sql


PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ API Globales ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
@@03-DELTAS\GLOBAL\CDSAPER.PKS
@@03-DELTAS\GLOBAL\CDSAPER.PKB
@@03-DELTAS\GLOBAL\CG_REF_CODES_TRG.sql


SPOOL OFF
COMMIT;





