PROMPT~~~~~~~~~~~~~~~~~~~~~~~~~~ GLOBAL ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@@05-INSERT\GLOBAL\PARAMETRE.sql
@@05-INSERT\GLOBAL\CG_REF_CODES.sql
@@05-INSERT\GLOBAL\DOMAINE.sql

@@05-INSERT\CSCI_RAP\CADRE_REFERENT.sql
@@05-INSERT\CSCI_RAP\UE.sql
@@05-INSERT\CSCI_RAP\PROCESSUS_APPRENTISSAGE.sql
@@05-INSERT\CSCI_RAP\EC.sql

@@05-INSERT\CSCI_ADM\ENSEIGNANT.sql
@@05-INSERT\CSCI_ADM\PROMOTION.sql
@@05-INSERT\CSCI_ADM\COMPAGNIE.sql
@@05-INSERT\CSCI_ADM\AUTHENTIFICATION_1.sql
@@05-INSERT\CSCI_ADM\ENTREPRISE.sql
@@05-INSERT\CSCI_ADM\EMPLOYE.sql
@@05-INSERT\CSCI_ADM\ETUDIANT.sql
@@05-INSERT\CSCI_ADM\AUTHENTIFICATION_2.sql
@@05-INSERT\CSCI_ADM\ROLE_PERMANENT.sql
@@05-INSERT\CSCI_ADM\ROLE.sql
@@05-INSERT\CSCI_ADM\ROLE_ANNUEL.sql
@@05-INSERT\CSCI_ADM\LETTRE.sql
@@05-INSERT\CSCI_ADM\CANDIDAT.sql

@@05-INSERT\CSCI_CON\REGROUPEMENT_RES.sql
@@05-INSERT\CSCI_CON\DOMAINE_RES.sql
@@05-INSERT\CSCI_CON\RUBRIQUE.sql
@@05-INSERT\CSCI_CON\RESSOURCE.sql

@@05-INSERT\CSCI_SAC\PRODUIT.sql

