create or replace TRIGGER CG$AIR_ETUDIANT AFTER INSERT ON ETUDIANT 
FOR EACH ROW 
BEGIN
  INSERT INTO STAGE (ANNEE_PRO, NO_ETUDIANT_NAT, NO_ENTREPRISE, NO_CONTACT_ILI, DATE_DEB, DATE_FIN, LIEU, INTITULE, SUJET) VALUES (:new.annee_pro, :new.no_etudiant_nat, '0', '0', SYSDATE, SYSDATE, 'Non Défini', 'Non Défini', 'Non Défini');
  NULL;
END;
/