-- INSERTING into ROLE
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (1,'RFO','Responsable de la formation','Recrutement des étudiants. Gestion des intervenants. Organisation et planification de l''année. Suivi du contrôle des connaissances. Organisation et suivi des stages. Gestionn du jury. Coordination des compagnies (avancement, cohérence, indépendance, etc...)');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (2,'RFE','Responsable du référentiel','Création, consolidation, adaptation et enrichissement du référentiel d''apprentissage : dispositif (principes, règles, séquencement, etc.), fiches d''aprentissage, produits et ressources pédagogiques associés. Garant du référentiel pédagogique et de son application. Relation avec Thales-IS');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (3,'RLO','Responsable logistique','Achat/Suivi  matériel. Suivi/Renouvellement des contrats avec les éditeurs. Approvisionnement des outils et des licences, des ouvrages, des revues professionnelles, etc.');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (4,'TDT','Tuteur de tuteur','Accompagnement et assistance aux tuteurs de compagnie et tuteurs d''activité : régulateur, modérateur et/ou médiateur');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (5,'TOG','Tuteur-Organisateur','Définition du cadre projet spécifique à sa compagnie : besoins matériels et logiciels, choix techniques et fonctionnels, cahier des charges, proposition technique et financière.');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (6,'TCP','Tuteur-Chef de projet','Organisation de chaque séquence d''apprentissage (ajustement, élaboration et régulations des parcours et des apprentissages individuels et coolectifs). Support et assistance au quotidien de chaque étudiant. Préparation et pilotage de la réunion d''avancement hebdomadaire.');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (7,'TCL','Tuteur-Client','Maîtrise d''ouvrage au travers d''un jeu de rôles pour les activités de capture des exigences, d''analyse, d''installation-déploiement, de recette, de maintenance (bugs, demande d''évolution).');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (8,'TAP','Tuteur d''apprentissage','Élaboration et mise à disposition du contexte et des ressources pédagogiques en lien avec l''activité abordée. Accompagnement et entrainement de chaque étudiant (Coaching). Conseil, réorientation, aide, régulation voire arbitrage en cas de blocage. Evaluation des apprentissages effectués.');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (9,'TSP','Tuteur Support','Support et/ou expertise sur l''un ou l''autre des 13 domaines d''apprentissage (Qualité, Gestion de Configuration Logiciel, Support Technique, etc.) indépendamment du suivi des apprentissages.');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (10,'TMD','Tuteur-Modérateur it2','Consolidation des produits de qualité moyenne (voire médiocre). Intervient essentiellement comme un pair sur lequel l''étudiant chef de projet ou les membres de l''équipe peuvent s''appuyer pour conforter leurs choix lors de la 2ieme itération.');
Insert into "ROLE" ("ID_ROL","SIGLE_ROL","DESIGNATION","COMMENTAIRE") values (11,'TRC','Tuteur-Responsable chargé d''affaire','Responsble hiérachique qui arbitre, régule, voire impose (respect des coûts et délais, arbitrage "hiérarchique" entre élèves). Assistance et support auprès de l''étudiant chef de projet.');
