DROP TABLE "AFFECTATION_CRR_ETU" CASCADE CONSTRAINTS;
DROP TABLE "AFFECTATION_ETUDIANT" CASCADE CONSTRAINTS;
DROP TABLE "AFFECTATION_PDT_VFAS" CASCADE CONSTRAINTS;
DROP TABLE "AFFECTATION_PRODUIT" CASCADE CONSTRAINTS;
DROP TABLE "AFFECTATION_RES_FA" CASCADE CONSTRAINTS;
DROP TABLE "AFFECTATION_RES_VFAS" CASCADE CONSTRAINTS;
DROP TABLE "AUTHENTIFICATION" CASCADE CONSTRAINTS;
DROP TABLE "AVENANT" CASCADE CONSTRAINTS;
DROP TABLE "BCK_LST_PATH" CASCADE CONSTRAINTS;
DROP TABLE "CADRE_REFERENT" CASCADE CONSTRAINTS;
DROP TABLE "CANDIDAT" CASCADE CONSTRAINTS;
DROP TABLE "CG_REF_CODES" CASCADE CONSTRAINTS;
DROP TABLE "CODE_NOTATION" CASCADE CONSTRAINTS;

DROP TABLE "COMPAGNIE" CASCADE CONSTRAINTS;
DROP TABLE "COMPTE_RENDU_REUNION" CASCADE CONSTRAINTS;
DROP TABLE "CONTACT_STAGE" CASCADE CONSTRAINTS;
DROP TABLE "CRITERE_ENTREPRISE" CASCADE CONSTRAINTS;
DROP TABLE "DIPLOME" CASCADE CONSTRAINTS;
DROP TABLE "DOMAINE" CASCADE CONSTRAINTS;
DROP TABLE "DOMAINE_RES" CASCADE CONSTRAINTS;
DROP TABLE "EC" CASCADE CONSTRAINTS;
DROP TABLE "EMPLOYE" CASCADE CONSTRAINTS;
DROP TABLE "ENSEIGNANT" CASCADE CONSTRAINTS;
DROP TABLE "ENTREPRISE" CASCADE CONSTRAINTS;
DROP TABLE "ENTREPRISE_JN" CASCADE CONSTRAINTS;
DROP TABLE "ETUDIANT" CASCADE CONSTRAINTS;
DROP TABLE "EVALUATION_ENTREPRISE" CASCADE CONSTRAINTS;
DROP TABLE "FA" CASCADE CONSTRAINTS;
DROP TABLE "FAS" CASCADE CONSTRAINTS;
DROP TABLE "FONCTION" CASCADE CONSTRAINTS;
DROP TABLE "INTERVENTION" CASCADE CONSTRAINTS;
DROP TABLE "INTERVENTION_COMPAGNIE" CASCADE CONSTRAINTS;
DROP TABLE "LETTRE" CASCADE CONSTRAINTS;
DROP TABLE "LST_FONCTION" CASCADE CONSTRAINTS;
DROP TABLE "NOTATION_STAGE" CASCADE CONSTRAINTS;
DROP TABLE "NOTE_ENTREPRISE" CASCADE CONSTRAINTS;
DROP TABLE "OFFRE_STAGE" CASCADE CONSTRAINTS;
DROP TABLE "PARAMETRE" CASCADE CONSTRAINTS;
DROP TABLE "POSTE_ENTREPRISE" CASCADE CONSTRAINTS;
DROP TABLE "PROCESSUS_APPRENTISSAGE" CASCADE CONSTRAINTS;
DROP TABLE "PRODUIT" CASCADE CONSTRAINTS;
DROP TABLE "PROMOTION" CASCADE CONSTRAINTS;
DROP TABLE "REGROUPEMENT_RES" CASCADE CONSTRAINTS;
DROP TABLE "RESSOURCE" CASCADE CONSTRAINTS;
DROP TABLE "ROLE" CASCADE CONSTRAINTS;
DROP TABLE "ROLE_ANNUEL" CASCADE CONSTRAINTS;
DROP TABLE "ROLE_PERMANENT" CASCADE CONSTRAINTS;
DROP TABLE "RUBRIQUE" CASCADE CONSTRAINTS;
DROP TABLE "SEQUENCE" CASCADE CONSTRAINTS;
DROP TABLE "SOUTENANCE" CASCADE CONSTRAINTS;
DROP TABLE "STAGE" CASCADE CONSTRAINTS;
DROP TABLE "STRUCTURE_EVALUATION" CASCADE CONSTRAINTS;
DROP TABLE "UE" CASCADE CONSTRAINTS;
DROP TABLE "VERSION" CASCADE CONSTRAINTS;
DROP TABLE "VFAS" CASCADE CONSTRAINTS;
DROP TABLE "VFAS_PA" CASCADE CONSTRAINTS;
DROP TABLE "VISITE_STAGE" CASCADE CONSTRAINTS;









